In [31]:
from transformers import AutoTokenizer, AutoModelForTextEncoding
from IPython.display import display
print = display

def tokenize(tokenizer, texts: str|list[str]):
    return tokenizer(
        texts,
        add_special_tokens=False,
        padding='max_length',
        truncation=True,
        max_length=6,
        return_tensors="pt"
    )

In [46]:
tokenizer_bert = AutoTokenizer.from_pretrained("distilbert-base-uncased")
print(tokenizer_bert.__dict__)
print(tokenizer_bert.pad_token)
print(tokenizer_bert.pad_token_id)
print(tokenize(tokenizer_bert, '[PAD]'))
print(tokenize(tokenizer_bert, 'Hello World [PAD]'))
print(tokenize(tokenizer_bert, ['Hello World', '']))

{'_tokenizer': <tokenizers.Tokenizer at 0x7f57b963a630>,
 '_decode_use_source_tokenizer': False,
 'init_inputs': (),
 'init_kwargs': {'do_lower_case': True,
  'unk_token': '[UNK]',
  'sep_token': '[SEP]',
  'pad_token': '[PAD]',
  'cls_token': '[CLS]',
  'mask_token': '[MASK]',
  'tokenize_chinese_chars': True,
  'strip_accents': None,
  'model_max_length': 512,
  'name_or_path': 'distilbert-base-uncased'},
 'name_or_path': 'distilbert-base-uncased',
 '_processor_class': None,
 'model_max_length': 512,
 'padding_side': 'right',
 'truncation_side': 'right',
 'model_input_names': ['input_ids', 'attention_mask'],
 'clean_up_tokenization_spaces': True,
 'split_special_tokens': False,
 'deprecation_warnings': {},
 '_in_target_context_manager': False,
 'chat_template': None,
 '_bos_token': None,
 '_eos_token': None,
 '_unk_token': '[UNK]',
 '_sep_token': '[SEP]',
 '_pad_token': '[PAD]',
 '_cls_token': '[CLS]',
 '_mask_token': '[MASK]',
 '_pad_token_type_id': 0,
 '_additional_special_tokens':

'[PAD]'

0

{'input_ids': tensor([[0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 0, 0, 0, 0, 0]])}

{'input_ids': tensor([[7592, 2088,    0,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1, 0, 0, 0]])}

{'input_ids': tensor([[7592, 2088,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])}

In [3]:
tokenizer_t5 = AutoTokenizer.from_pretrained("google/flan-t5-base")
print(tokenizer_t5.__dict__)
print(tokenizer_t5.pad_token)
print(tokenizer_t5.pad_token_id)
print(tokenize(tokenizer_t5, '[PAD]'))
print(tokenize(tokenizer_t5, 'Hello World [PAD]'))
print(tokenize(tokenizer_t5, ['Hello World', '[PAD]']))

{'_tokenizer': <tokenizers.Tokenizer at 0x7f57b9639830>,
 '_decode_use_source_tokenizer': False,
 'init_inputs': (),
 'init_kwargs': {'eos_token': AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
  'unk_token': AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
  'pad_token': AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
  'extra_ids': 100,
  'additional_special_tokens': ['<extra_id_0>',
   '<extra_id_1>',
   '<extra_id_2>',
   '<extra_id_3>',
   '<extra_id_4>',
   '<extra_id_5>',
   '<extra_id_6>',
   '<extra_id_7>',
   '<extra_id_8>',
   '<extra_id_9>',
   '<extra_id_10>',
   '<extra_id_11>',
   '<extra_id_12>',
   '<extra_id_13>',
   '<extra_id_14>',
   '<extra_id_15>',
   '<extra_id_16>',
   '<extra_id_17>',
   '<extra_id_18>',
   '<extra_id_19>',
   '<extra_id_20>',
   '<extra_id_21>',
   '<extra_id_22>',
   '<extra_id_23>',
   '<

'<pad>'

0

{'input_ids': tensor([[ 784, 3965,  308,  908,    0,    0]]), 'attention_mask': tensor([[1, 1, 1, 1, 0, 0]])}

{'input_ids': tensor([[8774, 1150,  784, 3965,  308,  908]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

{'input_ids': tensor([[8774, 1150,    0,    0,    0,    0],
        [ 784, 3965,  308,  908,    0,    0]]), 'attention_mask': tensor([[1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0]])}

In [27]:
tokenize(tokenizer_t5, ['Hello World', '<pad>', 'asdnaskjdnasd', 'A', '<extra_id_0>'])

{'input_ids': tensor([[ 8774,  1150,     0,     0,     0,     0],
        [    0,     0,     0,     0,     0,     0],
        [   38,    26,    29,     9,     7,   157],
        [   71,     0,     0,     0,     0,     0],
        [32099,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0]])}

In [55]:
print(tokenizer_bert.unk_token_id)
print(tokenizer_t5.unk_token_id)

100

2

In [80]:
import torch
torch.set_grad_enabled(False)
flant5_encoder = AutoModelForTextEncoding.from_pretrained('google/flan-t5-base').eval()
tokens = tokenize(tokenizer_t5, ['hello!', 'hello', 'hi', 'panel'])
z = flant5_encoder.forward(**tokens).last_hidden_state
print(tokens.input_ids)
print(z.shape)
print(z[0] @ z[1].T)
print(z[0] @ z[2].T)
print(z[0] @ z[3].T)

tensor([[21820,    55,     0,     0,     0,     0],
        [21820,     0,     0,     0,     0,     0],
        [ 7102,     0,     0,     0,     0,     0],
        [ 2952,     0,     0,     0,     0,     0]])

torch.Size([4, 6, 768])

tensor([[9.0845, 8.7947, 8.7947, 8.7947, 8.7947, 8.7947],
        [9.3018, 9.3946, 9.3946, 9.3946, 9.3946, 9.3946],
        [8.7500, 9.0515, 9.0515, 9.0515, 9.0515, 9.0515],
        [9.5683, 9.8422, 9.8422, 9.8422, 9.8422, 9.8422],
        [9.4612, 9.7255, 9.7255, 9.7255, 9.7255, 9.7255],
        [9.3690, 9.6484, 9.6484, 9.6484, 9.6484, 9.6484]])

tensor([[5.7617, 5.6379, 5.6379, 5.6379, 5.6379, 5.6379],
        [5.9998, 6.0905, 6.0905, 6.0905, 6.0905, 6.0905],
        [4.4810, 4.8266, 4.8266, 4.8266, 4.8266, 4.8266],
        [5.3295, 5.6353, 5.6353, 5.6353, 5.6353, 5.6353],
        [5.3032, 5.6060, 5.6060, 5.6060, 5.6060, 5.6060],
        [5.1105, 5.4193, 5.4193, 5.4193, 5.4193, 5.4193]])

tensor([[8.3215, 8.7553, 8.7553, 8.7553, 8.7553, 8.7553],
        [8.3254, 8.2437, 8.2437, 8.2437, 8.2437, 8.2437],
        [8.9605, 9.0942, 9.0942, 9.0942, 9.0942, 9.0942],
        [9.5316, 9.6606, 9.6606, 9.6606, 9.6606, 9.6606],
        [9.3429, 9.4575, 9.4575, 9.4575, 9.4575, 9.4575],
        [9.4272, 9.5588, 9.5588, 9.5588, 9.5588, 9.5588]])

In [81]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('google/flan-t5-base').eval()
z = model.forward(tokens).token_embeddings

print(z.shape)
print(z[0] @ z[1].T)
print(z[0] @ z[2].T)
print(z[0] @ z[3].T)

No sentence-transformers model found with name google/flan-t5-base. Creating a new one with MEAN pooling.


torch.Size([4, 6, 768])

tensor([[9.0845, 8.7947, 8.7947, 8.7947, 8.7947, 8.7947],
        [9.3018, 9.3946, 9.3946, 9.3946, 9.3946, 9.3946],
        [8.7500, 9.0515, 9.0515, 9.0515, 9.0515, 9.0515],
        [9.5683, 9.8422, 9.8422, 9.8422, 9.8422, 9.8422],
        [9.4612, 9.7255, 9.7255, 9.7255, 9.7255, 9.7255],
        [9.3690, 9.6484, 9.6484, 9.6484, 9.6484, 9.6484]])

tensor([[5.7617, 5.6379, 5.6379, 5.6379, 5.6379, 5.6379],
        [5.9998, 6.0905, 6.0905, 6.0905, 6.0905, 6.0905],
        [4.4810, 4.8266, 4.8266, 4.8266, 4.8266, 4.8266],
        [5.3295, 5.6353, 5.6353, 5.6353, 5.6353, 5.6353],
        [5.3032, 5.6060, 5.6060, 5.6060, 5.6060, 5.6060],
        [5.1105, 5.4193, 5.4193, 5.4193, 5.4193, 5.4193]])

tensor([[8.3215, 8.7553, 8.7553, 8.7553, 8.7553, 8.7553],
        [8.3254, 8.2437, 8.2437, 8.2437, 8.2437, 8.2437],
        [8.9605, 9.0942, 9.0942, 9.0942, 9.0942, 9.0942],
        [9.5316, 9.6606, 9.6606, 9.6606, 9.6606, 9.6606],
        [9.3429, 9.4575, 9.4575, 9.4575, 9.4575, 9.4575],
        [9.4272, 9.5588, 9.5588, 9.5588, 9.5588, 9.5588]])

In [86]:
model.forward(tokens).sentence_embedding

tensor([[-0.2834,  0.1011,  0.0958,  ..., -0.1644,  0.2118, -0.0417],
        [-0.1202,  0.1066, -0.3856,  ...,  0.0695,  0.1300,  0.0754],
        [ 0.0241,  0.1043, -0.4156,  ..., -0.0125,  0.0847,  0.0967],
        [-0.1193,  0.2418, -0.2466,  ..., -0.0072, -0.0075,  0.0690]])

# 내 모델 vs. GVQA weights

In [33]:
import torch
from ltvu.models.without_rgb.lightning_modules import TextOnlyNLQLitModule
from sentence_transformers import SentenceTransformer

lit = TextOnlyNLQLitModule(model_name='google/flan-t5-base', head_name='af')
# base_model = SentenceTransformer('google/flan-t5-base')
list(lit.model.lm[0].auto_model.state_dict().keys())

No sentence-transformers model found with name google/flan-t5-base. Creating a new one with MEAN pooling.


['shared.weight',
 'encoder.embed_tokens.weight',
 'encoder.block.0.layer.0.SelfAttention.q.weight',
 'encoder.block.0.layer.0.SelfAttention.k.weight',
 'encoder.block.0.layer.0.SelfAttention.v.weight',
 'encoder.block.0.layer.0.SelfAttention.o.weight',
 'encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight',
 'encoder.block.0.layer.0.layer_norm.weight',
 'encoder.block.0.layer.1.DenseReluDense.wi_0.weight',
 'encoder.block.0.layer.1.DenseReluDense.wi_1.weight',
 'encoder.block.0.layer.1.DenseReluDense.wo.weight',
 'encoder.block.0.layer.1.layer_norm.weight',
 'encoder.block.1.layer.0.SelfAttention.q.weight',
 'encoder.block.1.layer.0.SelfAttention.k.weight',
 'encoder.block.1.layer.0.SelfAttention.v.weight',
 'encoder.block.1.layer.0.SelfAttention.o.weight',
 'encoder.block.1.layer.0.layer_norm.weight',
 'encoder.block.1.layer.1.DenseReluDense.wi_0.weight',
 'encoder.block.1.layer.1.DenseReluDense.wi_1.weight',
 'encoder.block.1.layer.1.DenseReluDense.wo.weight',
 'enc

In [34]:
p_ckpt = '/data/gunsbrother/prjs/ltvu/llms/GroundVQA/GroundVQA/GroundVQA_B-NLQ_NaQ-finetune_NLQ-VLG-val_R1_03=29.7.ckpt'
state_dict = torch.load(p_ckpt, map_location='cpu')
list(state_dict['state_dict'].keys())

['model.v_emb',
 'model.lm.shared.weight',
 'model.lm.encoder.embed_tokens.weight',
 'model.lm.encoder.block.0.layer.0.SelfAttention.q.weight',
 'model.lm.encoder.block.0.layer.0.SelfAttention.k.weight',
 'model.lm.encoder.block.0.layer.0.SelfAttention.v.weight',
 'model.lm.encoder.block.0.layer.0.SelfAttention.o.weight',
 'model.lm.encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight',
 'model.lm.encoder.block.0.layer.0.layer_norm.weight',
 'model.lm.encoder.block.0.layer.1.DenseReluDense.wi_0.weight',
 'model.lm.encoder.block.0.layer.1.DenseReluDense.wi_1.weight',
 'model.lm.encoder.block.0.layer.1.DenseReluDense.wo.weight',
 'model.lm.encoder.block.0.layer.1.layer_norm.weight',
 'model.lm.encoder.block.1.layer.0.SelfAttention.q.weight',
 'model.lm.encoder.block.1.layer.0.SelfAttention.k.weight',
 'model.lm.encoder.block.1.layer.0.SelfAttention.v.weight',
 'model.lm.encoder.block.1.layer.0.SelfAttention.o.weight',
 'model.lm.encoder.block.1.layer.0.layer_norm.weight',

In [36]:
state_dict['state_dict']['model.v_emb'].shape

torch.Size([1, 1, 768])

In [17]:
state_dict['state_dict']['model.nlq_head.reg_head.head.0.conv.weight'].shape

torch.Size([384, 768, 3])